name: 'Import Superset Dashboard'
author: "Guy Attia"
description: 'Import dashboard ZIP file to Superset'
inputs:
  url_base:
    description: 'Base URL for your Superset API endpoint'
    required: true
    default: 'http://localhost:8088'
  dashboard_file_path: 
    description: 'Path of the dashboard you want to import'
    required: true
  overwrite:
    description: 'Boolean index if to allow overwriting an existing dashboard or not'
    required: false
    default: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.url_base }}
    - ${{ inputs.dashboard_file_path }}
    - ${{ inputs.overwrite }}
branding:
  color: blue
